using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ConfigBinder;

[Generator(LanguageNames.CSharp)]
public sealed class BindConfigGenerator : IIncrementalGenerator
{
    private const string FullAttributeName = "ConfigBinder.BindConfigAttribute";

    private const string Header = // lang=cs
		$"""
		//--------------------------------------------------------------------
		// <auto-generated>
		//	This code was generated by {ThisAssembly.Title}
		//	Runtime version: {ThisAssembly.Version}
		//
		// 	Changes to this file may cause incorrect behavior and will be lost if
		//	the code is regenerated.
		//</auto-generated>
		""";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("BindConfigAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));
        
        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                FullAttributeName,
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, ct) => GetModel(ctx, ct))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!)
            .Collect();
        
        context.RegisterSourceOutput(models, Emit);
    }

    private static ConfigModel? GetModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (ctx.Attributes.IsEmpty)
        {
            return null;
        }

        var attr = ctx.Attributes[0];

        if (attr.ConstructorArguments.IsEmpty)
        {
            return null;
        }

        if (attr.ConstructorArguments[0].Value is not string sectionName)
        {
            return null;
        }

        return new ConfigModel(
            FullyQualifiedName: symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            TypeName: symbol.Name,
            SectionName: sectionName);
    }

    private static void Emit(
        SourceProductionContext ctx,
        ImmutableArray<ConfigModel> models)
    {
        if (models.IsEmpty)
        {
            return;
        }

        foreach (var model in models)
        {
            ctx.AddSource(
                $"{model.SafeName}Validator.g.cs",
                SourceText.From(RenderValidator(model), Encoding.UTF8));
        }

        ctx.AddSource(
            "AddConfigExtensions.g.cs",
            SourceText.From(RenderExtensions(models), Encoding.UTF8));
    }


    private static string RenderValidator(ConfigModel m) => $$"""
        {{Header}}
        #nullable enable

        namespace ConfigBinder.Generated;

        internal sealed class {{m.SafeName}}Validator : global::Microsoft.Extensions.Options.IValidateOptions<{{m.FullyQualifiedName}}>
        {
            public global::Microsoft.Extensions.Options.ValidateOptionsResult Validate(
                string? name, {{m.FullyQualifiedName}} options)
            {
                var results = new global::System.Collections.Generic.List<global::System.ComponentModel.DataAnnotations.ValidationResult>();

                var valid = global::System.ComponentModel.DataAnnotations.Validator.TryValidateObject(
                    options,
                    new global::System.ComponentModel.DataAnnotations.ValidationContext(options),
                    results,
                    validateAllProperties: true);

                if (valid)
                {
                    return global::Microsoft.Extensions.Options.ValidateOptionsResult.Success;
                }

                var failures = new global::System.Collections.Generic.List<string>(results.Count);
                foreach (var r in results)
                {
                    failures.Add(r.ErrorMessage ?? "Unknown validation error.");
                }

                return global::Microsoft.Extensions.Options.ValidateOptionsResult.Fail(failures);
            }
        }
        """;

    private static string RenderExtensions(ImmutableArray<ConfigModel> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace ConfigBinder.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Extension methods generated by ConfigBinder.</summary>");
        sb.AppendLine("public static class GeneratedConfigExtensions");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all <c>[BindConfig]</c>-decorated types: binds each type");
        sb.AppendLine("    /// to its configuration section and, where applicable, registers a typed");
        sb.AppendLine("    /// <c>IValidateOptions&lt;T&gt;</c> that runs on startup.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedConfig(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var m in models)
        {
            sb.AppendLine($"        // {m.FullyQualifiedName} ← section \"{m.SectionName}\"");
            sb.AppendLine($"        services");
            sb.AppendLine($"            .AddOptions<{m.FullyQualifiedName}>()");
            sb.AppendLine($"            .BindConfiguration(\"{m.SectionName}\")");
            sb.AppendLine($"            .ValidateOnStart();");
            sb.AppendLine($"        services.AddSingleton<");
            sb.AppendLine($"            global::Microsoft.Extensions.Options.IValidateOptions<{m.FullyQualifiedName}>,");
            sb.AppendLine($"            global::ConfigBinder.Generated.{m.SafeName}Validator>();");
            sb.AppendLine();
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private const string AttributeSource = $$"""
        {{Header}}
        #nullable enable

        namespace ConfigBinder;

        /// <summary>
        /// Marks a configuration <c>class</c> or <c>record</c> for automatic registration:
        /// section binding, <c>IOptions&lt;T&gt;</c> wiring, and startup validation.
        /// <para>
        /// Usage (generic host): <c>services.AddGeneratedConfig()</c>
        /// </para>
        /// </summary>
        /// <remarks>
        /// Only reference types (<c>class</c> / <c>record class</c>) are supported because
        /// <c>OptionsBuilder&lt;TOptions&gt;.BindConfiguration()</c> requires <c>TOptions : class</c>.
        /// </remarks>
        [global::System.AttributeUsage(
            global::System.AttributeTargets.Class,
            AllowMultiple = false,
            Inherited = false)]
        public sealed class BindConfigAttribute : global::System.Attribute
        {
            /// <summary>The <c>IConfiguration</c> section key to bind from.</summary>
            public string SectionName { get; }

            /// <inheritdoc cref="BindConfigAttribute"/>
            public BindConfigAttribute(string sectionName) => SectionName = sectionName;
        }
        """;
}