namespace ConfigBinder.Sources;

internal static class SharedSources
{
	public const string Header = // lang=cs
		$"""
		 //----------------------------------------------------------------------------
		 // <auto-generated>
		 //	This code was generated by {ThisAssembly.PackageId}
		 //	Runtime version: {ThisAssembly.PackageVersion}
		 //
		 //    Changes to this file may cause incorrect behavior and will be lost if
		 //    the code is regenerated.
		 //</auto-generated>
		 //----------------------------------------------------------------------------
		 """;
}